# Generated by Django 4.1.4 on 2023-02-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_uz', models.CharField(max_length=200, verbose_name='Muallif[uz]')),
                ('author_en', models.CharField(max_length=200, verbose_name='Muallif[en]')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Nomi[uz]')),
                ('name_en', models.CharField(max_length=200, verbose_name='Nomi[en]')),
                ('keywords_uz', models.CharField(max_length=300, verbose_name="Kalit so'zlar[uz]")),
                ('keywords_en', models.CharField(max_length=300, verbose_name="Kalit so'zlar[en]")),
                ('short_data_uz', models.CharField(max_length=400, verbose_name='Anatatsiya[uz]')),
                ('short_data_en', models.CharField(max_length=400, verbose_name='Anatatsiya[en]')),
                ('references', models.CharField(max_length=500, verbose_name='Foydalanilgan adabiyotlar')),
                ('file_link', models.URLField(verbose_name='Kitob manzili')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqt')),
            ],
        ),
    ]
