# Generated by Django 4.1.4 on 2023-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Nomi[uz]')),
                ('name_en', models.CharField(max_length=200, verbose_name='Nomi[en]')),
                ('file_link', models.URLField(verbose_name='Journal manzili')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqt')),
            ],
        ),
    ]
