# Generated by Django 4.1.6 on 2023-02-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='articles',
            field=models.ManyToManyField(related_name='articles', to='mainapp.article'),
        ),
    ]
