# Generated by Django 4.1.6 on 2023-02-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_issue_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='first_page',
            field=models.IntegerField(default=0, verbose_name='Birinchi sahifasi'),
        ),
        migrations.AddField(
            model_name='article',
            name='last_page',
            field=models.IntegerField(default=0, verbose_name='Ohirgi sahifasi'),
        ),
    ]
