# Generated by Django 4.1.6 on 2023-02-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_article_first_page_article_last_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.issue', verbose_name='Jurnal soni'),
            preserve_default=False,
        ),
    ]
