# Generated by Django 4.1.6 on 2023-02-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_issue_articles_article_issue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Maqola', 'verbose_name_plural': 'Maqolalar'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Jurnal soni', 'verbose_name_plural': 'Jurnallar'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author_en',
            field=models.TextField(max_length=200, verbose_name='Muallif[en]'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_uz',
            field=models.TextField(verbose_name='Muallif[uz]'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords_en',
            field=models.TextField(verbose_name="Kalit so'zlar[en]"),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords_uz',
            field=models.TextField(verbose_name="Kalit so'zlar[uz]"),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=models.TextField(verbose_name='Foydalanilgan adabiyotlar'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_data_en',
            field=models.TextField(verbose_name='Anatatsiya[en]'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_data_uz',
            field=models.TextField(verbose_name='Anatatsiya[uz]'),
        ),
    ]
