# Generated by Django 4.1.6 on 2023-02-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_article_options_alter_issue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_en',
            field=models.TextField(help_text="⚠️Har bir muallifni ';'(nuqtali vergul) bilan ajratib yozing", max_length=200, verbose_name='Muallif[en]'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_uz',
            field=models.TextField(help_text="⚠️Har bir muallifni ';'(nuqtali vergul) bilan ajratib yozing", verbose_name='Muallif[uz]'),
        ),
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.issue', verbose_name='Jurnal soni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=models.TextField(help_text="⚠️Har bir adabiyotni ';'(nuqtali vergul) bilan ajratib yozing.", verbose_name='Foydalanilgan adabiyotlar'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateField(verbose_name='Kiritilgan vaqt'),
        ),
    ]
