# Generated by Django 4.1.6 on 2023-02-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_article_status_alter_article_author_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('open', 'Barcha uchun ochiq'), ('close', 'Barcha uchun yopiq')], default='open', max_length=18, verbose_name='Holati'),
        ),
    ]
