# Generated by Django 4.1.6 on 2023-04-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_issue_name_en_remove_issue_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='phone_number',
            field=models.CharField(default='Kiritilmagan', max_length=15, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_en',
            field=models.TextField(help_text="⚠️Har bir muallifni ';'(nuqtali vergul) bilan ajratib yozing!<br>Namuna: Alijonov Nodirbek;", max_length=200, verbose_name='Muallif[en]'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_uz',
            field=models.TextField(help_text="⚠️Har bir muallifni ';'(nuqtali vergul) bilan ajratib yozing!<br>Namuna: Alijonov Nodirbek;", verbose_name='Muallif[uz]'),
        ),
    ]
